import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";

const beauforForLOL = localFont({
  src: "./fonts/BeaufortforLOL-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${beauforForLOL.className} antialiased`}>
        <main>{children}</main>
        <Toaster position="bottom-right" closeButton richColors />
      </body>
    </html>
  );
}
